receta_conSeguridad:
    resource: "@uniRecetasBundle/Resources/config/routing/conSeguridad/recetaConSeguridad.yml"
    prefix:   /conSeguridad
    
receta:
    path:     /
    defaults: { _controller: "uniRecetasBundle:receta:index" }

receta_show:
    path:     /{id}/show
    defaults: { _controller: "uniRecetasBundle:receta:show" }
    
receta_categ_index:
    path:     /{id}/indexPorCat
    defaults: { _controller: "uniRecetasBundle:receta:indexPorCategoria" }