receta_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniRecetasBundle:receta:delete" }
    requirements: { _method: post|delete }
    
receta_new:
    path:     /new
    defaults: { _controller: "uniRecetasBundle:receta:new" }

receta_new_reccat:
    path:     /{id}/newreccat
    defaults: { _controller: "uniRecetasBundle:receta:newRecCat" }    
    
receta_save_reccat:
    path:     /save_reccat
    defaults: { _controller: "uniRecetasBundle:receta:saveRecCat" }
    requirements: { _method: post|put }
    
receta_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniRecetasBundle:receta:edit" }
    
receta_update2:
    path:     /update2
    defaults: { _controller: "uniRecetasBundle:receta:updateRec2" }
    requirements: { _method: post|put }